package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Abc2_Build3'
in the project with id = 'Abc2', and delete the patch script.
*/
create(RelativeId("Abc2"), BuildType({
    id("Abc2_Build3")
    name = "build3"
}))

